S3t6 build product services
iO-Academy/2022-aug-furniture-store-be pull request #17
Opened 2022-11-08 16:29 UTC by fatimaseghir

2022-11-08 16:32 UTC, O-MAY requested changes
Please add catagory validator.

2022-11-09 12:16 UTC, TherealGuah requested changes

2022-11-09 12:16 UTC, TherealGuah commented on categories.php
> -
Add line to keep file consistancy

2022-11-09 12:16 UTC, TherealGuah commented on src/Services/Validators/CategoryValidator.php
> +        $count = count($categories->getCategories()); // change to check for id, include try catch here
remove line and tidy up

2022-11-09 12:22 UTC, merged